server:
  port: 9000
spring:
  datasource:
    username: blocko
    password: blocko
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
    validationQuery: SELECT 1
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true
  devtools:
    livereload:
      nabled: true
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      globally_quoted_identifiers: true
      format_sql: false
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      show-sql: false
  session:
    store-type: jdbc
  